name: CI/CD TODO API

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/projets-sdv/todo-api

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u ${{ github.actor }} \
            --password-stdin

      - name: Define image tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}
